Models and migrations for User and Watchlist
jpgomezt/MovieTown pull request #4
Opened 2021-09-15 21:11 UTC by Snatiolam

This includes the models of User and Watchlist
It also contains the migrations for the above mentioned with some intemediate 
migrations between user_review and user_order. 
The intermediate migrations may fail due to the lack of the respective tables but commenting
each line that refers to foreignId for a table that has not been created should solve the problem.

2021-09-16 02:43 UTC, jpgomezt requested changes
Revisar los cambios solicitados

2021-09-16 02:43 UTC, jpgomezt commented on app/Models/Watchlist.php
> +            "name" => "required|boolean",
No se porque el nombre le pusiste que tiene que ser tipo boolean

2021-09-16 02:43 UTC, jpgomezt commented on app/Models/Watchlist.php
> +            "description" => "required|date",
No se porque la descripción le pusiste que tiene que ser tipo date

2021-09-16 02:43 UTC, jpgomezt commented on app/Models/Watchlist.php
> +        return $this->hasMany(Movie::class);
Es una relación many to many. 
Revisar porque en este caso se usa belongsToMany 
https://laravel.com/docs/8.x/eloquent-relationships#many-to-many

2021-09-16 02:43 UTC, jpgomezt commented on app/Models/Watchlist.php
> +
Faltan los getters y setters de user_id

2021-09-16 02:43 UTC, jpgomezt commented on database/migrations/2021_09_15_000000_create_user_order_table.php
> +<?php
Solo hay necesidad de crear migraciones intermedias cuando las relaciones son many to many
La relacion user order es one to many, no hay necesidad de migracion intermedia.
Eliminar

2021-09-16 02:43 UTC, jpgomezt commented on database/migrations/2021_09_15_000000_create_user_review_table.php
> +<?php
Solo hay necesidad de crear migraciones intermedias cuando las relaciones son many to many
La relacion user review es one to many, no hay necesidad de migracion intermedia.
Eliminar

2021-09-16 02:43 UTC, jpgomezt commented on database/migrations/2021_09_15_000001_create_user_watchlist_table.php
> +<?php
Solo hay necesidad de crear migraciones intermedias cuando las relaciones son many to many
La relacion user watchlist es one to many, no hay necesidad de migracion intermedia.
Eliminar

2021-09-17 15:49 UTC, Snatiolam commented
Ya se hicieron los cambios que se pidieron, menos el que verifica email.
Esta decision se tomo porque:
1. Esa verificacion se puede hacer en html
2. Se necesita instalar una dependecia rfc.
Por lo tanto no lo veo necesario por ahora, sin embargo, podemos mirar la posibilidad de incluir esto en el futuro.

2021-09-17 20:23 UTC, merged